### Accès à une route test

GET http://localhost:3000/v1/

### Find all boardgames
GET http://localhost:3000/v1/boardgames

### Find all categories
GET http://localhost:3000/v1/categories

### Ajout d'un boardgame

POST http://localhost:3000/v1/boardgames
content-type: application/json

{
    "name": "Villainous",
    "min_players": 2,
    "max_players": 6,
    "min_age": 10,
    "duration": "45 minutes",
    "picture_url": "https://cdn3.philibertnet.com/466405-large_default/villainous.jpg"
}

### Ajout d'une categorie

POST http://localhost:3000/v1/categories
content-type: application/json

{
    "name": "Role-play"
}

### SUPPRESSION d'une categorie

DELETE http://localhost:3000/v1/categories/6
content-type: application/json


