### Accès à une route test

GET http://localhost:3000/v1/

### Find
GET http://localhost:3000/v1/boardgames

### Ajout d'un boardgame

POST http://localhost:3000/v1/boardgames
content-type: application/json

{
    "name": "Villainous",
    "min_players": 2,
    "max_players": 6,
    "min_age": 10,
    "duration": "45 minutes",
    "picture_url": "https://cdn3.philibertnet.com/466405-large_default/villainous.jpg",
    "author_id": 1,
    "editor_id": 1,
    "difficulty_id": 1
}